import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";
import QueryProviders from "@/components/query-providers";


const iterFont = Inter({
  subsets: ['latin'],
  variable: '--font-inter'
})

export const metadata: Metadata = {
  title: "Jira Clone App",
  description: "Generated by create next app",
  icons: {
    icon: '/icon.svg'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={cn(iterFont.variable, `antialiased min-h-screen`)}
      >
        <QueryProviders>
          {children}
        </QueryProviders>
      </body>
    </html>
  );
}
